-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 19:16:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlybanhang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlybanhang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlybanhang` DEFAULT CHARACTER SET utf8 ;
USE `quanlybanhang` ;

-- -----------------------------------------------------
-- Table `quanlybanhang`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanhang`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanhang`.`oder_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`oder_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_order_id` INT(11) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `quantity` DOUBLE NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `total_money_product` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 225
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanhang`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanhang`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `level` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanhang`.`user_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`user_notification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT '0',
  `code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlybanhang`.`user_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanhang`.`user_order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `total_money_order` DOUBLE NULL DEFAULT NULL,
  `total_money_vat` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
